---
  - name: Reconfigure sshd server
    ansible.builtin.template:
      src: sshd_config.j2
      dest: /etc/ssh/sshd_config
      owner: root
      group: root
      mode: u=rw,g=r,o=r
    tags:
      - config